#!/bin/sh

check_conditions () {
  if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    echo "You can't create and attach from inside neovim"
    exit 1
  fi

  if [ -z "$2" ]; then
    echo "Provide second argument with session name"
    exit 1
  fi
}

case "$1" in
  list)
    abduco -l | awk '$NF ~ /^vmux-/ { gsub("vmux-", "", $NF); print($NF); }'
    ;;
  attach)
    check_conditions $*
    abduco -e '^g' -A "vmux-$2"
    ;;
  new)
    check_conditions $*
    export EDITOR=vmux-editor
    export NVIM_LISTEN_ADDRESS=/tmp/vmux-$2
    abduco -e '^g' -A "vmux-$2" vmux-editor
    ;;
  send)
    check_conditions $*
    export NVIM_LISTEN_ADDRESS=/tmp/vmux-$2
    shift 2
    nvr -s $*
    ;;
esac

